apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-mosheliya-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-mosheliya
  template:
    metadata:
      labels:
        app: demo-app-mosheliya
    spec:
      containers:
        - name: demo-app-mosheliya
          image: mosiko1234/demo-app-mosheliya:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-mosheliya-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo-app-mosheliya
